export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SIDE_DRAWER_TOGGLE = 'SIDE_DRAWER_TOGGLE';
export const SIDE_DRAWER_CLOSE = 'SIDE_DRAWER_CLOSE';

export const MODAL_CLOSE = 'MODAL_CLOSE';
export const MODAL_FETCH_SUCCESS = 'MODAL_FETCH_SUCCESS';
export const MODAL_FETCH_ERROR = 'MODAL_FETCH_ERROR';
export const MODAL_CLEAR_FETCH_ERROR = 'MODAL_CLEAR_FETCH_ERROR';
export const MODAL_FORM_HANDLER='MODAL_FORM_HANDLER';
export const MODAL_TOGGLE='MODAL_TOGGLE';

export const ORDER_FORM_HANDLER='ORDER_FORM_HANDLER';
export const ORDER_CLEAR_FETCH_ERROR='ORDER_CLEAR_FETCH_ERROR';
export const ORDER_CLEAR_FETCH_SUCCESS='ORDER_CLEAR_FETCH_SUCCESS';
export const ORDER_FORM_ERROR='ORDER_FORM_ERROR';
export const ORDER_FORM_LOADING='ORDER_FORM_LOADING';
export const ORDER_FORM_SUCCESS='ORDER_FORM_SUCCESS';

export const INPUT_CHECK_VALIDITY_BEFORE_SENT='INPUT_CHECK_VALIDITY_BEFORE_SENT';
