// AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// SIDEDRAWER
export const SIDE_DRAWER_TOGGLE = 'SIDE_DRAWER_TOGGLE';
export const SIDE_DRAWER_CLOSE = 'SIDE_DRAWER_CLOSE';

// MODAL FORM
export const MODAL_FETCH_ERROR = 'MODAL_FETCH_ERROR';
export const MODAL_FETCH_SUCCESS = 'MODAL_FETCH_SUCCESS';
export const MODAL_FETCH_CLEAR_ERROR = 'MODAL_CLEAR_FETCH_ERROR';
export const MODAL_FETCH_START = 'MODAL_FETCH_START';
export const MODAL_TOGGLE='MODAL_TOGGLE';
export const MODAL_CLOSE = 'MODAL_CLOSE';

// ORDER FORM
export const ORDER_FETCH_POST_CLEAR='ORDER_FETCH_POST_CLEAR';
export const ORDER_FETCH_POST_ERROR='ORDER_FETCH_POST_ERROR';
export const ORDER_FETCH_POST_LOADING='ORDER_FETCH_POST_LOADING';
export const ORDER_FETCH_POST_SUCCESS='ORDER_FETCH_POST_SUCCESS';
export const ORDER_FETCH_POST_START='ORDER_FETCH_POST_START';

// ORDERS PAGE
export const ORDERS_FETCH_GET_CLEAR='ORDERS_FETCH_GET_CLEAR';
export const ORDERS_FETCH_GET_ERROR='ORDERS_FETCH_GET_ERROR';
export const ORDERS_FETCH_GET_LOADING='ORDERS_FETCH_GET_LOADING';
export const ORDERS_FETCH_GET_SUCCESS='ORDERS_FETCH_GET_SUCCESS';
export const ORDERS_FETCH_GET_START='ORDERS_FETCH_GET_START';

export const INPUT_CHECK_VALIDITY_BEFORE_SENT='INPUT_CHECK_VALIDITY_BEFORE_SENT';
