export const SHOW_MORE_PORTFOLIO_ITEMS = 'SHOW_MORE_PORTFOLIO_ITEMS';

export const SIDE_DRAWER_TOGGLE = 'SIDE_DRAWER_TOGGLE';
export const SIDE_DRAWER_CLOSE = 'SIDE_DRAWER_CLOSE';

export const MODAL_CLOSE = 'MODAL_CLOSE';
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CONTENT_SEND = 'MODAL_CONTENT_SEND';
export const MODAL_ERROR = 'MODAL_ERROR';